apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/aws-containers/retail-store-sample-catalog:1.2.2
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "snowdb:3306"
            - name: DB_READ_ENDPOINT
              value: "snowdb:3306"
            - name: DB_NAME
              value: "sampledb"
            - name: DB_USER
              value: "catalog_user"
            - name: DB_PASSWORD
              value: "default_password"

            - name: PORT
              value: "8080"
            - name: DB_MIGRATE
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
