apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks_dev_
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - services
      - endpoints
      - persistentvolumeclaims
      - persistentvolumes
      - nodes
      - namespaces
      - configmaps
      - secrets
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks_dev_
subjects:
  - kind: User
    name: eks_dev_
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks_dev_
  apiGroup: rbac.authorization.k8s.io
